color: null
description: null
fieldLayouts:
  f11a2e18-2477-44f4-9857-ac5a96af4db0:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-08T11:14:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 45534926-4ddd-4d2e-8fe6-df9605bd1b54 # text
            handle: headingGear
            includeInCards: false
            instructions: null
            label: 'Heading Gear'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8354175b-9f36-4159-9667-be6e95a14a28
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-08T11:14:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 82230e9e-73fe-48b7-a22b-39ff2db81243 # img
            handle: gearImg
            includeInCards: false
            instructions: null
            label: 'gear Img'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: da5c4422-4e53-4154-a005-ac26678d6f65
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-08T11:14:00+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 45534926-4ddd-4d2e-8fe6-df9605bd1b54 # text
            handle: gearText
            includeInCards: false
            instructions: null
            label: 'gear Text'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7bfe6a7c-3fb9-486c-9f48-5492b18c9a03
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c3fbb7e4-2866-49ba-83b8-f769dc700c0c
        userCondition: null
handle: gear
hasTitleField: false
icon: null
name: Gear
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
