altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  225cf1a7-3085-4e4f-a2f5-38cc423b0c79:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-05T09:45:13+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 9ed83b95-d598-4a8a-8335-188a7fd72e32
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 99e14fae-784c-462a-bb59-8537b9a57e23
        userCondition: null
fs: upload
handle: uploads
name: Uploads
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
