columnSuffix: null
handle: storySlider
instructions: null
name: storySlider
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:292d97a9-bc1f-4260-a69a-b2a7c0a2c5c9' # Uploads
  defaultUploadLocationSubpath: null
  maintainHierarchy: false
  maxRelations: 6
  minRelations: 3
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:292d97a9-bc1f-4260-a69a-b2a7c0a2c5c9' # Uploads
  restrictedLocationSubpath: null
  selectionLabel: null
  showCardsInGrid: false
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:292d97a9-bc1f-4260-a69a-b2a7c0a2c5c9' # Uploads
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
