dateModified: 1757395303
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: '*'
      tableAttributes:
        - status
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - title
        - asc
      defaultViewMode: ''
      disabled: false
      key: singles
      tableAttributes:
        - status
        - link
      type: native
    -
      heading: Channels
      key: 'heading:3a6a6f85-109a-4735-8e2f-b751cebb5349'
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:1c391eb4-364d-4c98-80f8-4dcd7599cdfb' # Riders
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
    -
      defaultSort:
        - postDate
        - desc
      defaultViewMode: ''
      disabled: false
      key: 'section:55a22671-75a2-4df4-86e3-29a49e79d5c0'
      tableAttributes:
        - status
        - postDate
        - expiryDate
        - link
      type: native
email:
  fromEmail: tahasfs53@gmail.com
  fromName: motoventure
  transportType: craft\mail\transportadapters\Sendmail
fs:
  upload:
    hasUrls: true
    name: Upload
    settings:
      path: $ASSET_BASE_PATH
    type: craft\fs\Local
    url: $ASSET_BASE_URL
meta:
  __names__:
    0ee9617e-65fe-47c5-9496-6d4ba6a84570: Riders # Riders
    1c391eb4-364d-4c98-80f8-4dcd7599cdfb: Riders # Riders
    1e0a3dcf-4558-41af-b7d8-8d708588c55f: motoventure # motoventure
    2bd5e877-57f1-4644-b7af-6a48d7bcd866: story # story
    9daa6e13-8d20-4ccf-badd-4899f5bb0726: Gear # Gear
    9fa3fb42-c709-457a-99af-843722d2ee3f: 'Riders Fields' # Riders Fields
    292d97a9-bc1f-4260-a69a-b2a7c0a2c5c9: Uploads # Uploads
    0334aa1b-d207-4a46-993f-8e44fd7459f7: 'Stories Field' # Stories Field
    00380d6a-29ac-491d-987f-73211b05b090: storySlider # storySlider
    806d3562-2547-4dee-863d-7b987984fe44: 'page Builder' # page Builder
    955ec127-8a8c-4803-897a-42e3330eb5fe: Gear # Gear
    9326a226-f7d4-48b3-bf44-45175c2ea603: motoventure # motoventure
    62418d5f-4af6-41a3-a9e0-30dccf9cf06f: links # links
    73667ce1-3ca0-4d09-b00c-cae72b4b6b8c: 'riders List' # riders List
    82230e9e-73fe-48b7-a22b-39ff2db81243: img # img
    150361a2-28ba-4b82-9b8b-76f5eeb44f47: storiesHeading # storiesHeading
    3041478a-0d82-437d-89b5-a719b7118dc4: storiesField # storiesField
    45534926-4ddd-4d2e-8fe6-df9605bd1b54: text # text
    a74cc84d-eb39-449b-8092-8c9ca0e97a92: story # story
    c7c86019-3a63-4a80-95b7-58e7f14c1456: StoriesFields # StoriesFields
    cf9c2fcb-aac6-4ba3-b70a-1483d5da57c1: Stories # Stories
    d1b126a9-ec68-4a6d-82a1-9efd4b9d793e: hero # hero
    d35798ac-1168-423f-b8a6-fda5318b962f: Home # Home
    e99e79f6-6e95-4847-a985-94e21f444728: 'globals Heading' # globals Heading
    e2987978-22f5-47b4-a0b3-8d0ebda69925: hero # hero
    f55eab90-ff2a-4ef7-aeec-0a27630a84d8: home # home
system:
  edition: solo
  live: true
  name: motoventure
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
