defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: f55eab90-ff2a-4ef7-aeec-0a27630a84d8 # home
handle: home
maxAuthors: null
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  9326a226-f7d4-48b3-bf44-45175c2ea603: # motoventure
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
