defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 9fa3fb42-c709-457a-99af-843722d2ee3f # Riders Fields
handle: riders
maxAuthors: 1
name: Riders
propagationMethod: all
siteSettings:
  9326a226-f7d4-48b3-bf44-45175c2ea603: # motoventure
    enabledByDefault: true
    hasUrls: true
    template: riders/_entry.twig
    uriFormat: 'riders/{slug}'
type: channel
